name: Build and push image to github registry

on:
  push:
    tags:
      - '*'
jobs:
  func-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Define ENV VARS
        id: define_env
        run: echo "::set-output name=tag::${GITHUB_REF#refs/*/}"

      - name: Pull template
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: template store pull golang-http

      - name: Login to DockerHub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate dockerfiles for all functions
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: build -f roll20-scrapper.dev.yml --shrinkwrap

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push get-players func
        uses: docker/build-push-action@v2
        with:
          context: ./build/get-players/
          file: ./build/get-players/Dockerfile
          build-args: |
            GO111MODULE=off
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/get-players:latest-${{ steps.define_env.outputs.github-sha-short }}

      - name: Build and push join-game func
        uses: docker/build-push-action@v2
        with:
          context: ./build/join-game/
          file: ./build/join-game/Dockerfile
          build-args: |
            GO111MODULE=off
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/join-game:latest-${{ steps.define_env.outputs.tag }}