name: Build and push image to github registry

on:
  push:
    branches:
      - master
jobs:
  func-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Define ENV VARS
        id: define_env
        run: echo "::set-output name=github-sha-short::$(echo $GITHUB_SHA | cut -c 1-7)"
      - name: Pull template
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: template store pull golang-http

      - name: Replace target
        run: |
          sed -i 's/localhost:5000/${{secrets.DOCKER_USERNAME}}/' roll20-scrapper.dev.yml

      - name: OpenFaaS build and push
        uses: mrsimpson/action-openfaas-build@0.3.0
        with:
          stack-file: roll20-scrapper.dev.yml
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}